### ISSUE TITLE
Misleading colon

### ISSUE THREAD

**Issue by lennym** [k88hudson/git-flight-rules#3] opened 2014-07-28 22:59 UTC
The colon at the end of https://github.com/k88hudson/git-flight-rules/blame/master/README.md#L30 implies that running `git rebase -i master` is *how* you would ensure that `master` is up to date, where in fact there is an intermediate step which has been omitted.

Note: I would PR a fix for this, but I think my workflow here is subtly different to yours, so will leave it up to you to resolve how you please. Personally, I avoid ever doing anything with `master` (as opposed to `origin/master`), and so in this case would:

```
git fetch [-p] # always with -p purely out of habit for housekeeping purposes
git rebase -i origin/master
```

**Comment by RichardLitt** [comment] 2015-03-14 18:05
Hey @lennym, thanks. I'll remove that colon. 

Do you want to add in a section with your workflow? It would be appreciated.

**Comment by RichardLitt** [comment] 2015-05-21 05:39
@lennym feel free to make a PR for your workflow, we'd appreciate it. I'm going to close this now as the issue is resolved. Thanks!

**Closed by RichardLitt** 2015-05-21 05:39 UTC
