### ISSUE TITLE
Shall it recommend --force-with-lease instead of just `git push -f`?

### ISSUE THREAD

**Issue by vi** [k88hudson/git-flight-rules#120] opened 2017-11-08 16:10 UTC

**Comment by RichardLitt** [comment] 2017-11-08 16:34
This looks like a duplicate of #8. If you have a specific PR to make to suggest this, go ahead and add it. 

On another note, this really oughtn't to be a place for suggestions, but instead a list of flight rules - things which work to get you out of a bind, and actions which will help do the job in a minimum of effort. Sometimes, `push -f` is called for over `--force-with-lease`. Something to keep in mind.

**Comment by annmarielarue** [comment] 2017-11-21 06:43
content://media/external/file/620

**Closed** 2017-11-21 08:37 UTC

**Comment by annmarielarue** [comment] 2017-11-26 00:58
I don't understand
